apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-a
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: public.my-services.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 801  #port of service #basically all "domain-name/" requests would be forwarded to port of service 
                            #but only forwarded to tea-svc service that contains the dice app
      - path: /gift/(.*)
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 801  #port of service #basically all "domain-name/gift/" requests would be forwarded to port of service 
                            #but only forwarded to coffee-svc service that contains the gift app
